### ISSUE TITLE
Misleading debug statement in src/limits.c

### ISSUE THREAD

**Issue by johnzozo** [sudo-project/sudo#101]
The debug statement logs the value of ```dumpflag``` instead of the actual value set: 0

https://github.com/sudo-project/sudo/blob/109a0331a530626efd157d2f657b3b0526dc70fd/src/limits.c#L211-L214 

The debug statement should look something like: 
```sudo_debug_printf(SUDO_DEBUG_ERROR|SUDO_DEBUG_ERRNO, "prctl(PR_SET_DUMPABLE, 0, 0, 0, 0)"); ```

**Comment by loneicewolf** [comment]
can confirm I was a bit confused by this for awhile, glad someone else also saw this

**Comment by millert** [comment]
Thanks, I've fixed the cut & pasto in 51cbc62
