### ISSUE TITLE
Allow skipping fingerprint pam module when using -A

### ISSUE THREAD

**Issue by jankatins** [sudo-project/sudo#112]
I have a fingerprint reader on my laptop and fedora configures `pam_fprintd.so` to be tried before `pam_unix.so`. When I run sudo as part of a script (pyinfra in my case, but ansible has [the](https://github.com/ansible/ansible/issues/73308) [same](https://github.com/ansible/ansible/issues/3345) [problem](https://bugs.freedesktop.org/show_bug.cgi?id=66629)), no `tty` is there so `sudo` will authenticate every call. Unfortunately, `sudo` now waits for the `pam_fprintd.so` to timeout (or me authenticating it) and then use `pam_unix.so` which asks for a password and gets one via the `SUDO_ASKPASS` command.

Given that `sudo` knows that the authentication should happen via password, it makes no sense to ask for the fingerprint, but I currently see no way to disable `pam_fprintd.so` in only such cases. 

One solution for this (in sudo) would be if `sudo` could install a separate `pam.d` service for cases where it's called with `-A`. A user (or hopefully distros/`authselect`) could then configure authentications for such cases without `pam_fprintd.so` (or just add the `pam_unix.so` earlier than `pam_fprintd.so`).

**Comment by millert** [comment]
The changes are present in the 1.9.9 release.

**Comment by jankatins** [comment]
Thank you!

**Comment by jankatins** [comment]
If someone searches for it: I wrote up how to setup this so you do not get bothered by getting asked to authenticate via fingerprint if you use a script to call `sudo -A/--ask-pass`: https://www.katzien.de/en/posts/2022-02-06-sudo-with-fingerprint-support/
