### ISSUE TITLE
plugins/sudoers/ldap_util.c cuts off last char of role cn

### ISSUE THREAD

**Issue by johnzozo** [sudo-project/sudo#115]
The calculated size doesn't account for the space between sudoRole and the CN which results in the last character of the LDAP role cn being cutoff by snprintf.

https://github.com/sudo-project/sudo/blob/4fef09e1c2e30e9cd2a8142279807d43376634c8/plugins/sudoers/ldap_util.c#L481-L484

A correction could look something like:
`size_t slen = sizeof("sudoRole ") + strlen(priv->ldap_role);`

**Comment by millert** [comment]
Thanks, I used your suggested fix in e23874d
