### ISSUE TITLE
Manual does not state exactly what is passed to the shell’s `-c` option for options `--login` and `--shell`

### ISSUE THREAD

**Issue by Rinzwind** [sudo-project/sudo#121]
The description of `--login` and `--shell` in the manual may need some clarification on what command (if any) is passed to the shell, it currently only says “If a command is specified, it is passed to the shell for execution via the shell's `-c` option”:

https://github.com/sudo-project/sudo/blob/7baee707b003d943b13dcbc34f0937f2f740fea3/docs/sudo.man.in#L442-L454

https://github.com/sudo-project/sudo/blob/7baee707b003d943b13dcbc34f0937f2f740fea3/docs/sudo.man.in#L621-L629

Specifically, the escaping rules applied could use some clarification. I personally got a bit confused about this:

```
$ sudo --login echo $'\'$USER\''
'root'
```

Not being equivalent to this:

```
# echo '$USER'
$USER
# bash -c $'echo \'$USER\''
$USER
```

Or to this:

```
# echo \'\$USER\'
'$USER'
# bash -c $'echo \\\'\\$USER\\\''
'$USER'
```

But rather to this:

```
# echo \'$USER\'
'root'
# bash -c $'echo \\\'$USER\\\''
'root'
```

Possible clarification:

> If a command is specified, it is passed to the shell’s `-c` option as the concatenation of the command and all its arguments separated by spaces, after escaping each character (including spaces) through a slash, except for the alphanumerics, underscores, hyphens and dollar signs.

This is based on:

https://github.com/sudo-project/sudo/blob/7baee707b003d943b13dcbc34f0937f2f740fea3/src/parse_args.c#L634-L642

It could perhaps be explicitly noted that, at least in the case of bash, the resulting [shell command](https://www.gnu.org/software/bash/manual/bash.html#Shell-Commands) is always a [simple command](https://www.gnu.org/software/bash/manual/bash.html#Simple-Commands): “A simple shell command such as `echo a b c` consists of the command itself followed by arguments, separated by spaces. More complex shell commands are composed of simple commands arranged […]”. This touches on three different meanings for ‘command’ (shell command, simple command, command), which may have (also) been the source of confusion for a closely related issue: #78, “-s option command string manipulation”. Using the example from that issue, in `sudo -s "whoami; whoami"`, the `whoami; whoami` is passed as the command in a simple command, not as a shell command consisting of a [list](https://www.gnu.org/software/bash/manual/bash.html#Lists) of two simple commands.

**Comment by millert** [comment]
The changes are present in the 1.9.9 release.

**Comment by Rinzwind** [comment]
Thank you!

Something I will note here just for future reference is that `ssh` behaves differently, see: https://github.com/openssh/openssh-portable/pull/139.

So using `ssh`:

```
$ ssh ${destination:?} echo foo ';' echo bar
foo
bar
$ bash -c 'echo foo ; echo bar'
foo
bar
$ echo foo ; echo bar
foo
bar
```

This is akin to using [`eval`](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#eval):

```
$ eval echo foo ';' echo bar
foo
bar
```

Versus using `sudo`:

```
$ sudo --login echo foo ';' echo bar
foo ; echo bar
$ bash -c 'echo foo \; echo bar'
foo ; echo bar
$ echo foo \; echo bar
foo ; echo bar
```
