### ISSUE TITLE
Multiple memory leaks were detected through fuzz_sudoers

### ISSUE THREAD

**Issue by nora-pxh** [sudo-project/sudo#128]
Hello，multiple memory leaks were detected through fuzz_sudoers.

[testcase-fuzz_sudoers-202112020001.zip](https://github.com/sudo-project/sudo/files/7807810/testcase-fuzz_sudoers-202112020001.zip)

==63107==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 768 byte(s) in 24 object(s) allocated from:
    # 0 0x522a82 in calloc /src/llvm-project/compiler-rt/lib/asan/asan_malloc_linux.cpp:154:3
    # 1 0x56708a in new_member /src/sudo/plugins/sudoers/gram.y:1283:14
    # 2 0x5627c6 in sudoersparse /src/sudo/plugins/sudoers/gram.y:1111:25
    # 3 0x556351 in LLVMFuzzerTestOneInput /src/fuzz_sudoers.c:286:5
......
Direct leak of 256 byte(s) in 8 object(s) allocated from:
    # 0 0x522a82 in calloc /src/llvm-project/compiler-rt/lib/asan/asan_malloc_linux.cpp:154:3
    # 1 0x56708a in new_member /src/sudo/plugins/sudoers/gram.y:1283:14
    # 2 0x561529 in sudoersparse /src/sudo/plugins/sudoers/gram.y:396:25
    # 3 0x556351 in LLVMFuzzerTestOneInput /src/fuzz_sudoers.c:286:5
......
Direct leak of 188 byte(s) in 22 object(s) allocated from:
    # 0 0x5228ed in malloc /src/llvm-project/compiler-rt/lib/asan/asan_malloc_linux.cpp:145:3
    # 1 0x59004a in fill /src/sudo/plugins/sudoers/./toke_util.c:75:11
    # 2 0x5870a9 in sudoerslex /src/sudo/plugins/sudoers/toke.l:725:13
    # 3 0x55fe59 in sudoersparse /src/sudo/plugins/sudoers/gram.c:1544:16
    # 4 0x556351 in LLVMFuzzerTestOneInput /src/fuzz_sudoers.c:286:5
......
Direct leak of 128 byte(s) in 4 object(s) allocated from:
    # 0 0x522a82 in calloc /src/llvm-project/compiler-rt/lib/asan/asan_malloc_linux.cpp:154:3
    # 1 0x56708a in new_member /src/sudo/plugins/sudoers/gram.y:1283:14
    # 2 0x561628 in sudoersparse /src/sudo/plugins/sudoers/gram.y:422:25
    # 3 0x556351 in LLVMFuzzerTestOneInput /src/fuzz_sudoers.c:286:5
......
Direct leak of 96 byte(s) in 3 object(s) allocated from:
    # 0 0x522a82 in calloc /src/llvm-project/compiler-rt/lib/asan/asan_malloc_linux.cpp:154:3
    # 1 0x56708a in new_member /src/sudo/plugins/sudoers/gram.y:1283:14
    # 2 0x561edd in sudoersparse /src/sudo/plugins/sudoers/gram.y:387:25
    # 3 0x556351 in LLVMFuzzerTestOneInput /src/fuzz_sudoers.c:286:5
......
Direct leak of 89 byte(s) in 7 object(s) allocated from:
    # 0 0x5228ed in malloc /src/llvm-project/compiler-rt/lib/asan/asan_malloc_linux.cpp:145:3
    # 1 0x5907ff in fill_cmnd /src/sudo/plugins/sudoers/./toke_util.c:128:38
    # 2 0x5837d6 in sudoerslex /src/sudo/plugins/sudoers/toke.l:712:13
    # 3 0x55fe59 in sudoersparse /src/sudo/plugins/sudoers/gram.c:1544:16
    # 4 0x556351 in LLVMFuzzerTestOneInput /src/fuzz_sudoers.c:286:5
......
Direct leak of 29 byte(s) in 10 object(s) allocated from:
    # 0 0x5228ed in malloc /src/llvm-project/compiler-rt/lib/asan/asan_malloc_linux.cpp:145:3
    # 1 0x59004a in fill /src/sudo/plugins/sudoers/./toke_util.c:75:11
    # 2 0x5866a2 in sudoerslex /src/sudo/plugins/sudoers/toke.l:644:13
    # 3 0x55fe59 in sudoersparse /src/sudo/plugins/sudoers/gram.c:1544:16
    # 4 0x556351 in LLVMFuzzerTestOneInput /src/fuzz_sudoers.c:286:5
......
Direct leak of 16 byte(s) in 1 object(s) allocated from:
    # 0 0x522a82 in calloc /src/llvm-project/compiler-rt/lib/asan/asan_malloc_linux.cpp:154:3
    # 1 0x5623c4 in sudoersparse /src/sudo/plugins/sudoers/gram.y:747:24
    # 2 0x556351 in LLVMFuzzerTestOneInput /src/fuzz_sudoers.c:286:5
......
Direct leak of 6 byte(s) in 1 object(s) allocated from:
    # 0 0x5228ed in malloc /src/llvm-project/compiler-rt/lib/asan/asan_malloc_linux.cpp:145:3
    # 1 0x5907ff in fill_cmnd /src/sudo/plugins/sudoers/./toke_util.c:128:38
    # 2 0x5895ca in sudoerslex /src/sudo/plugins/sudoers/toke.l:706:10
    # 3 0x55fe59 in sudoersparse /src/sudo/plugins/sudoers/gram.c:1544:16
    # 4 0x556351 in LLVMFuzzerTestOneInput /src/fuzz_sudoers.c:286:5
......
Indirect leak of 273 byte(s) in 28 object(s) allocated from:
    # 0 0x5228ed in malloc /src/llvm-project/compiler-rt/lib/asan/asan_malloc_linux.cpp:145:3
    # 1 0x59004a in fill /src/sudo/plugins/sudoers/./toke_util.c:75:11
    # 2 0x5870a9 in sudoerslex /src/sudo/plugins/sudoers/toke.l:725:13
    # 3 0x55fe59 in sudoersparse /src/sudo/plugins/sudoers/gram.c:1544:16
    # 4 0x556351 in LLVMFuzzerTestOneInput /src/fuzz_sudoers.c:286:5
......
Indirect leak of 80 byte(s) in 1 object(s) allocated from:
    # 0 0x522a82 in calloc /src/llvm-project/compiler-rt/lib/asan/asan_malloc_linux.cpp:154:3
    # 1 0x561f20 in sudoersparse /src/sudo/plugins/sudoers/gram.y:496:30
    # 2 0x556351 in LLVMFuzzerTestOneInput /src/fuzz_sudoers.c:286:5
......
Indirect leak of 72 byte(s) in 1 object(s) allocated from:
    # 0 0x522a82 in calloc /src/llvm-project/compiler-rt/lib/asan/asan_malloc_linux.cpp:154:3
    # 1 0x561293 in sudoersparse /src/sudo/plugins/sudoers/gram.y:360:30
    # 2 0x556351 in LLVMFuzzerTestOneInput /src/fuzz_sudoers.c:286:5
......
Indirect leak of 64 byte(s) in 2 object(s) allocated from:
    # 0 0x522a82 in calloc /src/llvm-project/compiler-rt/lib/asan/asan_malloc_linux.cpp:154:3
    # 1 0x56708a in new_member /src/sudo/plugins/sudoers/gram.y:1283:14
    # 2 0x561edd in sudoersparse /src/sudo/plugins/sudoers/gram.y:387:25
    # 3 0x556351 in LLVMFuzzerTestOneInput /src/fuzz_sudoers.c:286:5
......
Indirect leak of 32 byte(s) in 1 object(s) allocated from:
    # 0 0x522a82 in calloc /src/llvm-project/compiler-rt/lib/asan/asan_malloc_linux.cpp:154:3
    # 1 0x56708a in new_member /src/sudo/plugins/sudoers/gram.y:1283:14
    # 2 0x561adb in sudoersparse /src/sudo/plugins/sudoers/gram.y:1140:25
    # 3 0x556351 in LLVMFuzzerTestOneInput /src/fuzz_sudoers.c:286:5
......
Indirect leak of 32 byte(s) in 1 object(s) allocated from:
    # 0 0x522a82 in calloc /src/llvm-project/compiler-rt/lib/asan/asan_malloc_linux.cpp:154:3
    # 1 0x56708a in new_member /src/sudo/plugins/sudoers/gram.y:1283:14
    # 2 0x562d0f in sudoersparse /src/sudo/plugins/sudoers/gram.y:934:25
    # 3 0x556351 in LLVMFuzzerTestOneInput /src/fuzz_sudoers.c:286:5
......
Indirect leak of 32 byte(s) in 1 object(s) allocated from:
    # 0 0x522a82 in calloc /src/llvm-project/compiler-rt/lib/asan/asan_malloc_linux.cpp:154:3
    # 1 0x56708a in new_member /src/sudo/plugins/sudoers/gram.y:1283:14
    # 2 0x561529 in sudoersparse /src/sudo/plugins/sudoers/gram.y:396:25
    # 3 0x556351 in LLVMFuzzerTestOneInput /src/fuzz_sudoers.c:286:5
......
Indirect leak of 30 byte(s) in 7 object(s) allocated from:
    # 0 0x5228ed in malloc /src/llvm-project/compiler-rt/lib/asan/asan_malloc_linux.cpp:145:3
    # 1 0x59004a in fill /src/sudo/plugins/sudoers/./toke_util.c:75:11
    # 2 0x5866a2 in sudoerslex /src/sudo/plugins/sudoers/toke.l:644:13
    # 3 0x55fe59 in sudoersparse /src/sudo/plugins/sudoers/gram.c:1544:16
    # 4 0x556351 in LLVMFuzzerTestOneInput /src/fuzz_sudoers.c:286:5
......

SUMMARY: AddressSanitizer: 2191 byte(s) leaked in 122 allocation(s).

**Comment by millert** [comment]
How did you build sudo when fuzzing it?  I don't see those leaks when sudo is configured and built with --enable-sanitizer and --enable-fuzzer.  If you don't configure sudo with --disable-leaks (implied by --enable-sanitizer) you will see leaks like when there is a sudoers syntax error.

**Comment by nora-pxh** [comment]
Thank you for your reply.
I used build.sh of the following commit file to compile. 
https://github.com/google/oss-fuzz/commit/191d8a640c37008310ee8ebccd291ab75c5cd8f6

**Comment by millert** [comment]
@nora-pxh That version of build.sh is old, you should either use the current version in the oss-fuzz repo or just follow the steps in https://www.sudo.ws/security/fuzzing/
