### ISSUE TITLE
Mention no-new-privileges flag

### ISSUE THREAD

**Issue by DemiMarie** [sudo-project/sudo#129]
In my experience, the most common reason for sudo not having euid 0 is that the no-new-privileges flag is set, which means that suid binaries do not work.

**Comment by millert** [comment]
Is that usually from running a container with the no-new-privileges flag set?

**Comment by DemiMarie** [comment]
In my case, it was running under bwrap, which always sets that flag.

**Comment by millert** [comment]
I've added a check for the no_new_privileges flag so sudo should now give a better error message if it is set.

**Comment by DemiMarie** [comment]
Thanks!
