### ISSUE TITLE
sudo -nv is slow and counts as a failed login

### ISSUE THREAD

**Issue by ZimbiX** [sudo-project/sudo#131]
[As part of my shell prompt](https://github.com/ZimbiX/dotfiles/blob/fc6a5c8c324485640bf88fd67741946e7695ee0d/zsh/prompt.zsh#L98-L106), I have a call to `sudo -nv` to be able to display whether sudo credentials are currently cached. Upon updating my system today, I noticed that my shell prompt was incredibly slow to show up after each command, and tracked it down to this command using `set -e`. In generating a number of slow prompts in quick succession, I ended up locking my account for several minutes! Thankfully, a reboot cleared that.

Expected behaviour: `sudo -nv` (`sudo --non-interactive --validate`) returns instantly no matter whether credentials are cached; and if they aren't, does not count it as a failed login.

Without cached credentials:

```
➜ time sudo -nv
sudo: a password is required
sudo -nv  0.00s user 0.01s system 0% cpu 1.937 total
```

With cached credentials:

```
➜ time sudo -nv 
sudo -nv  0.01s user 0.00s system 86% cpu 0.012 total
```

Version:

```
➜ sudo --version
Sudo version 1.9.9
Sudoers policy plugin version 1.9.9
Sudoers file grammar version 48
Sudoers I/O plugin version 1.9.9
Sudoers audit plugin version 1.9.9
```

I am assuming that the bug lies here, but I don't know a lot about sudo, so am not certain.

Edit: It looks like this is related to this section of the [1.9.9 release notes](https://github.com/sudo-project/sudo/releases/tag/SUDO_1_9_9):

> - When sudo is run in non-interactive mode (with the `-n` option), it will now attempt PAM authentication and only exit with an error if user interaction is required. This allows PAM modules that don't interact with the user to succeed. Previously, sudo would not attempt authentication if the `-n` option was specified. [Bug #956](https://bugzilla.sudo.ws/show_bug.cgi?id=956) and [GitHub issue #83](https://github.com/sudo-project/sudo/issues/83).

Edit 2: Downgrading to Arch package `sudo-1.9.8.p2-3` resolves the issue.

**Comment by freswa** [comment]
Bisected to `521ef37aeaa8899928a83e8d6b7a5858894e18b5`. Can confirm the issue.

**Comment by lkrms** [comment]
It's unclear if this is related to the same issue (if not, please let me know and I'll open a separate one), but in addition to the delay, I've found that `sudo -nv` always prints `We trust you have received the usual lecture` message in 1.9.9. I haven't configured any `lecture` settings explicitly, and other `sudo` commands print nothing, as usual.

**Comment by millert** [comment]
85fef8b restores the pre-1.9.9 behavior and adds a new sudoers option, noninteractive_auth, to enable to 1.9.9 behavior.
