### ISSUE TITLE
Changes to the environment from PAM bleed through sudo

### ISSUE THREAD

**Issue by aowi** [sudo-project/sudo#137]
I'm honestly not sure if this is a bug or a feature, so I appreciate any input on the issue.

In brief: If a pam module sets or changes the environment of the sudo process, these changes make it through to the invoked process.

In my specific case, pam_krb5 will set KRB5CCNAME unless configured not to do so. This variable will be set to `/tmp/krb5cc_$UID` and the variable will make it into envp of the exec'd process:

```
aowi@aowi ~ $ sudo -l
Matching Defaults entries for aowi on aowi:
    !lecture, tty_tickets, !fqdn, env_keep-=HOME, env_delete+=KRB5CCNAME
User aowi may run the following commands on aowi:
    (alice) NOPASSWD: /usr/bin/env
    (bob) /usr/bin/env
aowi@aowi ~ $ sudo -u alice /usr/bin/env|grep KRB
aowi@aowi ~ $ sudo -u bob /usr/bin/env|grep KRB
[sudo] password for aowi:
KRB5CCNAME=/tmp/krb5cc_0
aowi@aowi ~ $ sudo -u bob /usr/bin/env|grep KRB
aowi@aowi ~ $
```

No password prompt, no PAM: no variable.

As far as I can tell, there is no way to prevent this, since env_delete/env_keep appear to be applied before pam gets involved. The UID 0 in the variable is also a hint that this was set during the setuid'd sudo operation.

Is it intentional or desired, that changes made by pam are preserved?

P.S.
For anyone who stumbles on this through a search engine in the future: set the `noccache` flag for the pam_krb5 module config in /etc/pam.d. Check /etc/pam.d/sudo to figure out which file it gets included from.

**Comment by millert** [comment]
This is considered a feature.  Sudo uses the pam_getenvlist() function to get the environment variables set by a PAM module and merges them into the environment that is passed to the command.  For example, this is how the environment variables set by the pam_env module end up in the program's environment.  This happens after the sudoers environment handling.

**Comment by millert** [comment]
Environment changes made by PAM modules are considered "trusted" and are not subject to the same restrictions as the invoking user's environment.

**Comment by aowi** [comment]
All right, thanks for the fast clarification. I spent a fair whack of time trying to work out why env_delete didn't help, but what you're saying makes sense, and it's the pam module doing the wrong thing anyway in this case (better to not create the cache in the first place than to filter out the variable).

Have a great day!
