### ISSUE TITLE
new CPU flag prevents running on i686/Geode LX

### ISSUE THREAD

**Issue by perkelix** [sudo-project/sudo#140]
As reported [downstream](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1004894), recent recent SUDO releases use CPU flags that make 'sudo' dump core on x86-32 CPUs that don't offer all the newest and coolest hardening bells and whistles. It would be desirable to either revert those changes or make them --configurable.

**Comment by millert** [comment]
The hardening options are configurable via --disable-hardening.  They are used by default if the toolchain supports them.  The only real difference between 1.9.8 and 1.9.9 are the use of -fcf-protection and -Wl,-z,now, if supported.  Of those, -fcf-protection seems like the most likely, though the gcc docs claim it should work for i686 and above.

You can explicitly disable its use by passing ax_cv_check_ldflags___fcf_protection=no to configure.

**Comment by millert** [comment]
This really seems like a gcc problem, https://gcc.gnu.org/bugzilla/show_bug.cgi?id=104713

**Comment by millert** [comment]
Closing since this is an issue with the compiler, not sudo.  For Debian builds, it is probably simplest to run configure with --disable-hardening and just use Debian's own hardening rules.

**Comment by Zugschlus** [comment]
How big is the loss for all other i686 devices if we disable hardening for the i686 build? I apologize, but I simply cannot judge what consequences this has for other devices.

**Comment by perkelix** [comment]
This still isn't fixed.

**Comment by millert** [comment]
It will not be fixed in sudo, which is why I closed the issue.  As I said earlier, you can disable that flag by passing `ax_cv_check_ldflags___fcf_protection=no` to configure.

**Comment by perkelix** [comment]
The bug was not about how to explitly disable the flag. It was about sudo's configure having introduced incorrect assumptions about which flags are available on specific architectures. Contrary to what you've stated earlier, this is very much a sudo issue. It is not a compiler issue.

**Comment by millert** [comment]
Sudo's configure includes a test for whether the compiler supports the flag.  I don't think it is sudo's fault if the flag is supported by the compiler but the resulting code does not work.  You clearly disagree but I will not be changing this.  Since Debian builds have their own hardening flags there's really no need to use sudo's so this could be easily fixed in Debian.

**Comment by Zugschlus** [comment]
I have decided (for Debian) not to reduce the package's security level to allow it to run on the ancient geode architecture. Debian Users are free to refer to the technical committee to have this decision reverted. My recommendation is to use one of the alternatives, such as doas or su or a locally compiled sudo.
