### ISSUE TITLE
SUDO_COMMAND not being set when using sudoedit

### ISSUE THREAD

**Issue by mperry2** [sudo-project/sudo#141]
I'm using Sudo version 1.9.5p2 on Debian 11. I'm not sure if this is a bug, a misunderstanding, or a misconfiguration.

When I run sudoedit the `SUDO_COMMAND` environment variable is not being set. My expectation from reading the docs is that it should be. My editor needs to see the value of `SUDO_COMMAND` so it can parse it and set the correct filetype based on the original file's path and filename.

My /etc/sudoers:

```
Defaults        env_reset
Defaults        mail_badpass
Defaults        secure_path="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
root    ALL=(ALL:ALL) ALL
%sudo   ALL=(ALL:ALL) ALL
@includedir /etc/sudoers.d
```

Using this shell script named `sudoenv.sh`:

```
#!/bin/bash
set |grep ^SUDO
```

I testing by doing the following:

```
mperry@laptop:~$ sudo ./sudoenv.sh /root/foobar
SUDO_COMMAND='./sudoenv.sh /root/foobar'
SUDO_GID=1000
SUDO_UID=1000
SUDO_USER=mperry
mperry@laptop:~$ SUDO_EDITOR=$HOME/sudoenv.sh sudoedit /root/foobar
SUDO_EDITOR=/home/mperry/sudoenv.sh
sudoedit: /root/foobar unchanged
```

My expectation was that the invocation using sudoedit would also output the other `SUDO_*` variables.

**Comment by millert** [comment]
The sudo man page says this about sudoedit:

    Unlike most commands run by sudo, the editor is run with the invoking user's environment unmodified.

so I don't think this can be considered a bug.  That said, I can see how it would be useful to have this information available.

**Comment by mperry2** [comment]
OK, so clearly a misunderstanding on my part. Thanks for pointing that out. I found a workaround which is to use the following shell function.

```
function sudoedit() {
    SUDO_COMMAND="sudoedit $@" command sudoedit "$@"
}
```

That works just fine, so I'm going to close this issue.
