### ISSUE TITLE
A typo in man page produced from docs/visudo.man.in. Is int meant to be in? Is it deliberate?

### ISSUE THREAD

**Issue by ZjYwMj** [sudo-project/sudo#144]
Quoting [visudo.man.in](https://github.com/sudo-project/sudo/blob/main/docs/visudo.man.in):
```
133    An alternative is to place a colon-separated list of
134    \(lqsafe\(rq
135    editors int the
136    \fIeditor\fR
137    variable.
```
The word ``int`` at line 135 looks to me a typo. Is it meant to be in, or into? Is it deliberate?
As an aside, how could I write here a direct link to the line, and word, in question?

**Comment by millert** [comment]
Fixed by [72794ec](https://github.com/sudo-project/sudo/commit/72794ecd7595d8d1548f2c357007a69e1e8d5314)
