### ISSUE TITLE
fix NOW

### ISSUE THREAD

**Issue by eliekh05** [sudo-project/sudo#145]
We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

[sudo] password for eliekh05:

and i DO NOT KNOW THE PASSWORD AND I DID NOT RECEIVE ANYTHING

**Comment by millert** [comment]
I'm sorry, but if you don't know the password for the account there really isn't any way for me to help you.  It sounds like you need to contact whoever created the account.
