### ISSUE TITLE
huge improvement

### ISSUE THREAD

**Issue by eliekh05** [sudo-project/sudo#159]
this is a huge improvement over like 5 years if you can make GUI of your app that will be a huge improvement trust me #feature #request

**Comment by 10maurycy10** [comment]
A gui for sudo? Are you a bot?

**Comment by eliekh05** [comment]
i am not a bot

**Comment by millert** [comment]
I'm not sure what exactly you ask asking for.  It is already possible to use a GUI program for password entry with "sudo -A" as long as an askpass program is set either in /etc/sudo.conf or via the SUDO_ASKPASS environment variable.  Any _askpass_ program compatible with OpenSSH should work with sudo such as ssh-askpass or gnome-ssh-askpass.

**Comment by theAkito** [comment]
This is obviously a troll or some kid who started using Linux 2 hours and 10 minutes ago.

I would recommend not wasting any time on this issue and just close it.

**Comment by theAkito** [comment]
P.S.: He uses pound signs in his comment. Maybe he accidentally landed here, thinking this is a Twitter page or something.
