### ISSUE TITLE
Is it safe to call non-reentrant functions in signal processing functions?

### ISSUE THREAD

**Issue by BornThisWay** [sudo-project/sudo#181]
https://github.com/sudo-project/sudo/blob/63efad271a13124d739d536e9f5bf1dd110c3a1a/lib/util/event.c#L346

In this function:
1. It uses a static data structure. (Is it possible to be modified by others during use?)
2. Standard I/O functions are called. (non-reentrant)

The UNIX Specification describes the functions that guarantee call security in the signal processing program. 
Therefore, I have some doubts about the implementation of this function, please help to solve it, thank you.

**Comment by millert** [comment]
Sudo is single-threaded so there is no problem with multiple access. Also, standard I/O is **not** used, only the write(2) system call which is safe to use from a signal handler.

**Comment by millert** [comment]
Also, access to

**Comment by BornThisWay** [comment]
Okay, thank you for your answer.
