### ISSUE TITLE
sudo -U <user> -l as root does not display some entries correctly

### ISSUE THREAD

**Issue by aayla-secura** [sudo-project/sudo#183]
An entry like the following:

```
test ALL = () /bin/ls
```

would allow user `test` to run both `ls` as themselves (the invoking user). When `sudo -l` is invoked by user `test` this is shown correctly. But when `root` runs `sudo -U test -l`, the output implies user `test` can run `ls` as `root`:

```
# sudo -U test -l
User test may run the following commands on ip-172-31-28-2:
    (root) /bin/ls
```

**Comment by millert** [comment]
This is fixed by [6a0f7cc](https://github.com/sudo-project/sudo/commit/6a0f7ccc4118a66ab1e722c43d56cd81c50ed563)
```
# sudo -U test -l

User test may run the following commands on xerxes:
    (test) /bin/ls
```
