### ISSUE TITLE
sudo ssh cpu load

### ISSUE THREAD

**Issue by x0r3n** [sudo-project/sudo#187]
Hi. I have a problem with CPU load, with every sudo version (include development) and only on ubuntu 22.04.
If I change the user with "sudo" e.g. "sudo su user" and then ssh to another machine, then disconnect the ssh connection properly or just close the console with X (dosen't matter ), the ssh remains stuck on the original machine and loads 100% of the CPU. Only in ubuntu 22.04 and only with sudo. If I become a root first and after it I use "su user" than ssh doesn't stick for example, it works fine with that.

**Comment by millert** [comment]
I haven't noticed this on my Ubuntu 22.04 system but I will try to reproduce it.  Are you running the command in a new pty?  In other words, do you have use_pty, log_input or log_output in sudoers?  Also, do you see the same behavior when you use "sudo -i -u user" instead of "sudo su user"?

**Comment by millert** [comment]
You can enable sudo debugging with a line like the following in /etc/sudo.conf.
```
Debug sudo /var/log/sudo_debug all@debug
```

Also, `strace` output when the sshd is spinning could be helpful.
