### ISSUE TITLE
When sudo_mmap_strdup fails, copy[x] may be leaked?

### ISSUE THREAD

**Issue by BornThisWay** [sudo-project/sudo#202]
https://github.com/sudo-project/sudo/blob/ad220d72d425f5f13f9c299289d7edd2ad58ce78/src/sudo_intercept.c#L99

I don't think the resource rollback is complete.

**Comment by millert** [comment]
Fixed by [9c694e9](https://github.com/sudo-project/sudo/commit/9c694e9a658787f58fdbe1c81e6ed6387a6ce9b4)
