### ISSUE TITLE
sudo_mmap_strdup_v1: A null pointer may be accessed.

### ISSUE THREAD

**Issue by BornThisWay** [sudo-project/sudo#204]
https://github.com/sudo-project/sudo/blob/9c694e9a658787f58fdbe1c81e6ed6387a6ce9b4/lib/util/mmap_alloc.c#L119

`newstr` may be a null pointer..

**Comment by millert** [comment]
Fixed by [496ae6e](https://github.com/sudo-project/sudo/commit/496ae6e6f0308004eaf690c9e78f314830f702c2)
