### ISSUE TITLE
intercept_read: The print statement will never be executed to.

### ISSUE THREAD

**Issue by BornThisWay** [sudo-project/sudo#207]
https://github.com/sudo-project/sudo/blob/496ae6e6f0308004eaf690c9e78f314830f702c2/src/exec_intercept.c#L670

We should print and then return?

**Comment by millert** [comment]
Yes, the debug info should come before the return.

**Comment by millert** [comment]
Fixed by [6a5546b](https://github.com/sudo-project/sudo/commit/6a5546b11f0ec8a277af8563f3b98d9c75b0625c)
