### ISSUE TITLE
Found two spelling errors

### ISSUE THREAD

**Issue by BornThisWay** [sudo-project/sudo#209]
https://github.com/sudo-project/sudo/blob/6a5546b11f0ec8a277af8563f3b98d9c75b0625c/plugins/sudoers/parse.c#L211

settngs -> settings 

https://github.com/sudo-project/sudo/blob/6a5546b11f0ec8a277af8563f3b98d9c75b0625c/plugins/python/regress/testhelpers.h#L78

deitialization -> deinitialization

**Comment by millert** [comment]
Fixed by [c3f138e](https://github.com/sudo-project/sudo/commit/c3f138eaa23021cb75fb1632b4311a3e302a124e)
