### ISSUE TITLE
sudo_rcstr_dup: A null pointer may be dereferenced.

### ISSUE THREAD

**Issue by BornThisWay** [sudo-project/sudo#211]
https://github.com/sudo-project/sudo/blob/3396267291328eccfcbc7bfb1729c77f30216513/lib/util/rcstr.c#L52

**Comment by millert** [comment]
Merged [da7a5ec](https://github.com/sudo-project/sudo/commit/da7a5ecabd359fd65a79566851423ea6accad9f6)
