### ISSUE TITLE
Critical Path Traversal 

### ISSUE THREAD

**Issue by SleepTheGod** [sudo-project/sudo#215]
curl https://www.sudo.ws/ftp/etc/passwd
root:*:0:0:Charlie &:/root:/bin/csh
daemon:*:1:31:The devil himself:/root:/sbin/nologin
operator:*:2:5:System &:/operator:/sbin/nologin
bin:*:3:7:Binaries Commands and Source,,,:/:/sbin/nologin
www:*:67:67:HTTP server:/var/www:/sbin/nologin
ftp:*:98:20:Anonymous FTP:/usr/home/ftp:/usr/bin/false
nobody:*:32767:32767:Unprivileged user:/nonexistent:/sbin/nologin
millert:*:8036:20:Todd C. Miller:/usr/home/millert:/usr/local/bin/tcsh

**Comment by millert** [comment]
That's just a placeholder file inside a chroot jail for the ftp directory.  It's only purpose is to map user IDs to names for ftp.sudo.ws. There is no sensitive information there and you don't have access to the filesystem outside the chroot jail.

**Comment by SleepTheGod** [comment]
> That's just a placeholder file inside a chroot jail for the ftp directory. It's only purpose is to map user IDs to names for ftp.sudo.ws. There is no sensitive information there and you don't have access to the filesystem outside the chroot jail.

I can't take this comment seriously because I definitely would be concerned having my backed exposed like this ......

**Comment by millert** [comment]
https://www.sudo.ws/ftp is just the web view of ftp://ftp.sudo.ws/.
