### ISSUE TITLE
Doesn't work with my custom OS, Please make an exception.

### ISSUE THREAD

**Issue by daboltgod** [sudo-project/sudo#220]
I'd like to talk to you about working together to get my os working with sudo. 

Best way to contact me is probably through discord:
My Discord: DaBoltGod#6947

Please leave a comment when you add me :)

Thanks,
Da Bolt,

**Comment by millert** [comment]
sudo should work on most POSIX-compatible systems.  If your OS implements POSIX then it shouldn't be difficult to get sudo running.  If not, there really isn't much point in trying to use sudo on it.  If you find that there are changes needed to the configure script or sudo itself, please open a pull request.
