### ISSUE TITLE
sudo is not executing the right calling path when using symlinks

### ISSUE THREAD

**Issue by radosroka** [sudo-project/sudo#228]
When there are multiple symlinks with the same target in sudoers sudo will always execute the last one.

Sudo version:

sudo-1.9.8-5.p2.fc36.x86_64

Here is the reproducer:

```
[root@bbb ~]# mkdir dir1 dir2 common
[root@bbb ~]# printf '#! /bin/bash\necho $0\n' > common/script
[root@bbb ~]# chmod 700 common/script
[root@bbb ~]# ln -s ../common/script dir1/script
[root@bbb ~]# ln -s ../common/script dir2/script
[root@bbb ~]# echo 'ALL ALL = (root) NOPASSWD: /root/dir1/script,/root/dir2/script' >> /etc/sudoers
[root@bbb ~]#
[root@bbb ~]# /root/dir1/script
/root/dir1/script
[root@bbb ~]# /root/dir2/script
/root/dir2/script
[root@bbb ~]# sudo /root/dir1/script
/root/dir2/script
[root@bbb ~]# sudo /root/dir2/script
/root/dir2/script
```

**Comment by millert** [comment]
Sudo matches files by basename + inode and executes the path listed in the sudoers file, not the user-specified path.  Since the last match wins, that is what gets executed.  Changing this behavior is non-trivial and has the potential to introduce other, more serious, bugs.

**Comment by millert** [comment]
I believe this can be fixed by canonicalizing the command's parent directory (both the user-supplied command and the command in the sudoers file) and using that to distinguish between commands with the same basename and the same device/inode combination.  This is something I will investigate for sudo 1.9.14.

**Comment by sscheib-rh** [comment]
That's great news, thanks @millert :)

**Comment by millert** [comment]
This is fixed by [0ef5373](https://github.com/sudo-project/sudo/commit/0ef537367884d657ed7f9433eebf01a02130a1b4) and [b52631e](https://github.com/sudo-project/sudo/commit/b52631e8777ae9334e403259d211fb980aebc848).

**Comment by sscheib-rh** [comment]
That is awesome. Thanks a lot!

**Comment by millert** [comment]
Sudo 1.9.14 is out now and canonicalizes patch names before matching.
