### ISSUE TITLE
Merge Multiple Sudoer files from disparate hosts

### ISSUE THREAD

**Issue by TylerReese** [sudo-project/sudo#23]
I have several hosts, each with their own sudoer file.  I would like to merge all those sudoer files into one file so I can distribute a single file through a 3rd party configuration management tool.  cvtsudoers does some conversion and could be used for this purpose.

**Comment by edneville** [comment]
Have you set your rules up with `Host_Alias`? If not, this feels like a scripting task.

Could you give an example of expected input/output from the solution? I sort of feel that diff/patch could do the merge but could require some human help, ordering of complex rules might need some thought.

**Comment by millert** [comment]
cvtsudoers now has experimental merge support
