### ISSUE TITLE
Avoid logging Passwords by matching password prompts

### ISSUE THREAD

**Issue by TylerReese** [sudo-project/sudo#24]
As a sudo administrator I want to avoid logging passwords in IOlogs so I don't have an end user's password

One way this could be accomplished is to provide a mechanism that allows me to write a regular expression that I can match a password prompt that can exclude the logging of text when that prompt is reached.

**Comment by millert** [comment]
The log_passwords and passprompt_regex options can now be used for this.  Support will be included in sudo 1.9.10.
