### ISSUE TITLE
visudo: error if a user is called "list"

### ISSUE THREAD

**Issue by frukto** [sudo-project/sudo#246]
In 1.9.13p1 `visudo` reports an error if "as_whom"(_Runas_Member_) is literally  `list`:

```sh
alice ALL=(list) NOPASSWD: /usr/bin/cmd
           ^~~~
What now?
```

Apparently this is handled as a syntax error now. This behavior was not present in 1.9.12p2-1 and may be related to the new list pseudo command introduced in 1.9.13?

Edit: As a workaround the _Runas_Member_ can be quoted, this works in 1.9.13p1 and previous versions:
```sh
alice ALL=("list") NOPASSWD: /usr/bin/cmd
```

1.9.13p1 just landed in Debian 12 (bookworm)

**Comment by millert** [comment]
Thanks for reporting this, that was an unintended side-effect when the "list" command was added.  I just committed a fix associated tests for the issue.

**Comment by frukto** [comment]
:partying_face:  That was quick, awesome! Thank you for fixing this, @millert. From my side, you may close the issue.
