### ISSUE TITLE
`sudo -l -U someuser` fails when given command to check

### ISSUE THREAD

**Issue by tik-stbuehler** [sudo-project/sudo#248]
Given this entry:

```
nobody ALL = (root) NOPASSWD: /usr/bin/ping
```

As root: `sudo -l -U nobody` includes the command in the output, but `sudo -l -U nobody /usr/bin/ping` fails.

This got broken in 9f695f0fcc749b3cdebc453ba4fdeae84114f3ae (#134).

I think the idea was to check whether the user running this is allowed to run the pseudo command `list` as the target user, but `runas_pw` should only be set this way when testing for `list`, not when searching for the actual command.

**Comment by millert** [comment]
Fixed in 1.9.13p3
