### ISSUE TITLE
--disable-rpath ， It's not working on my machine.

### ISSUE THREAD

**Issue by BornThisWay** [sudo-project/sudo#250]
![image](https://user-images.githubusercontent.com/3735810/222728802-3afce819-d4e5-4f6b-a5b1-9583a6356c11.png)
Linux：5.10.0
aarch64
gcc: 10.3.1

**Comment by millert** [comment]
That option just prevents the -R option from being passed to the linker with each directory specified with -L.  It does not prevent the ELF RPATH or RUNPATH from being set.

**Comment by BornThisWay** [comment]
ok, thanks
