### ISSUE TITLE
bash with log_subcmds on AIX

### ISSUE THREAD

**Issue by loopway** [sudo-project/sudo#289]
Calling `sudo bash` on AIX with enabled `log_subcmds` breaks STDOUT of certain commands like `df`.  STDOUT is not displayed at all. For other commands like `ps` it seems to have no affect.

Tested with:
AIX 7300-01-02-2320
sudo 1.9.14-2 RPM (from sudo.ws Prebuilt Packages)
bash 5.1.4.0 LPP (AIX 7.3)
bash 5.1.16-1 RPM (from IBM AIX Toolbox for Open Source Software)

`sudo ksh` works as expected.

**Comment by millert** [comment]
I've added scaffolding to support both 32-bit and 64-bit versions of sudo_intercept.a on AIX in 980e0216ac12e89fe79797da43b513921e41e37b, 0a181849a123108ded6ba6de62d1712434c16a0d and 002e22f84614b2c1cf71f7e33a86dea3d16ac14c.  My sudo 1.9.15 AIX packages will include 32-bit and 64-bit versions of sudo_intercept.a.

**Comment by loopway** [comment]
@millert Thanks a lot for looking into it. I can confirm that we have no issue with the /opt/freeware/bin/bash_32 binary. Will be happy to test the new 1.9.15 release with 32 and 64 bit bash. 😎

**Comment by millert** [comment]
Closing now that sudo 1.9.15 is out.
