### ISSUE TITLE
RFE: Bug tracking system preference

### ISSUE THREAD

**Issue by opty77** [sudo-project/sudo#292]
Please mention your bug tracking system preference.

https://www.sudo.ws/docs/contributing/#filing-bug-reportsissues and https://github.com/sudo-project/sudo/blob/4b5480cf767bcb5548bda1555648ad5999b9a4a2/docs/CONTRIBUTING.md?plain=1#L13 don't match with https://github.com/sudo-project/sudo/blob/4b5480cf767bcb5548bda1555648ad5999b9a4a2/README.md?plain=1#L88

**Comment by opty77** [comment]
But not in the same order so I'm wondering which one do you prefer.

BTW, first ones mention e-mail too.

**Comment by millert** [comment]
I've made the two bug reporting sections consistent now.  It doesn't really matter to me whether people report bugs in bugzilla or GitHub.  I've run the bugzilla instance for a very long time but filing a bug requires making an account so using GitHub is simpler for people who already have a GitHub account.
