### ISSUE TITLE
Ｃould you please help me

### ISSUE THREAD

**Issue by trackers-lover** [sudo-project/sudo#319]
When I execute sudo ls, sudo will read the  /etc/sudoers file to determine if the current user has permission to access it. However, if I want sudo to read other files under /etc, which files should I modify? 
      Thanks !!

**Comment by trackers-lover** [comment]
i seem to have found the answer,  pathname.in.h, right?

**Comment by millert** [comment]
If you want to change the directory that the sudoers file lives in you can use the --sysconfdir configure option.  If you want to change the name from sudoers to something else, you can modify the value of _PATH_SUDOERS in plugins/sudoers/Makefile (the CPPDEFS variable).
