### ISSUE TITLE
Error building 1.9.15rc1 with MIT kerberos

### ISSUE THREAD

**Issue by rbgarga** [sudo-project/sudo#320]
I already added a comment on commit I believe is the one that introduced the problem - 2440174954217e01a2e285cb209a58f05d7f25ac

It seems `ctx` is not available in that context.  Here is a full log:

https://idaho.arrakis.com.br/data/main-amd64-default/2023-10-31_08h44m46s/logs/errors/sudo-1.9.15rc1.log

**Comment by rbgarga** [comment]
Fixed by #321

**Comment by millert** [comment]
Thanks for the fix.  I've added a build with kerberos support to the CI pipeline so I can catch problems like this earlier.
