### ISSUE TITLE
how to test sudo -b?

### ISSUE THREAD

**Issue by trackers-lover** [sudo-project/sudo#328]
Can you tell me how to test the sudo - b parameter?

**Comment by AlexBaranowski** [comment]
**It depends on what you want to test.** The easiest way to check if this parameter works at all is to invoke some long command ex. sleep.

```bash
sudo -b sleep 15.0
```

Then you can check that this is running.
```bash
sudo ps aux | egrep '[s]leep'
```

Example output for the interactive run:
```
[Alex@NormandySR2 ~]$ sudo -b sleep 15.0
[Alex@NormandySR2 ~]$ ps aux | egrep '[s]leep'
root       23100  0.0  0.0 238312  5072 pts/1    S    19:09   0:00 sudo -b sleep 15.0
root       23105  0.0  0.0 220952  1792 pts/1    S    19:09   0:00 sleep 15.0
[Alex@NormandySR2 ~]$ sudo pstree -lp 23100
sudo(23100)───sleep(23105)
```

Finally, the whole test might require a little parsing if you want to automate it.
