### ISSUE TITLE
sudo | pv | sudo turns off echo in terminal

### ISSUE THREAD

**Issue by allhavebrainimplantsandmore** [sudo-project/sudo#337]
When I run `sudo btrfs send -p| pv | sudo btrfs receive` my GNOME terminal stops showing the typed input suddenly. It works and runs what I type but it doesn't show it on the screen. 

`stty -a` before and after shows that this turns off echo and other attributes. The workaround is to run everything in `bash -c " "`. 

`stty -a` diff:
Before: `icrnl ixon isig icanon iexten echo -tostop`
After: `-icrnl -ixon -isig -icanon -iexten -echo tostop`

**Comment by millert** [comment]
What version of sudo are you running?

**Comment by allhavebrainimplantsandmore** [comment]
> What version of sudo are you running?

1.9.14-1.p3.fc39 (fedora)

**Comment by millert** [comment]
I believe this is fixed in the latest version of sudo (1.9.15p4) but as a workaround you can disable _use_pty_ in /etc/sudoers with a line like:

```
Defaults !use_pty
```

I can also provide you with a Fedora 29 rpm to try if you would like.

**Comment by allhavebrainimplantsandmore** [comment]
> use_pty

Thanks but I'll wait for the upstream version to get to the vanilla repo in F39. Disabling use_pty has security ramifications obviously.
