### ISSUE TITLE
After upgrade, sudo suddenly shows lecture again

### ISSUE THREAD

**Issue by haarp** [sudo-project/sudo#342]
Hello,

using sudo on Gentoo Linux. After upgrading from `1.9.14_p3` to `1.9.15_p2`, sudo suddenly for the first time in a long time, shows the lecture when run.

I know this can be controlled with the `lecture` setting. The problem is the sudden appearance of the lecture. It made me wary, thinking I was on the wrong server, or somebody was MITMing my sudo prompt. This caused a thorough investigation of my security.

The `lecture` option is not defined in any config. My user **does** have a file in `/var/db/sudo/lectured`. After confirming the lecture again, there is now a file with my user ID in that dir.

Please don't change any defaults this way :)

Thanks!

**Comment by haarp** [comment]
Ah, finally tracked this down to commit 7363ad7b3230b7b03a83f6. I guess that makes sense. Still, there should've been a migration to prevent admin panic :)

**Comment by millert** [comment]
This is mentioned both in the release notes and upgrade notes.

**Comment by haarp** [comment]
Whoops! So few projects bother to maintain release/upgrade notes that it didn't even cross my mind. I thought it was some kind of bug at first. Thanks for maintaining such notes tho!

I also see you added a migration now. Thanks a lot!
