### ISSUE TITLE
Memory leak in function 'get_editor'

### ISSUE THREAD

**Issue by JoraGevorgyan** [sudo-project/sudo#350]
The memory leak is found by a static analyzer developed at [CAST]( https://www.linkedin.com/company/cast-center/).

The memory allocated [at line 387](https://github.com/sudo-project/sudo/blob/eb4506f434a2b8060b2d398879c26e1f9c56f488/plugins/sudoers/visudo.c#L387) may left without free in case of exit from [line 404](https://github.com/sudo-project/sudo/blob/eb4506f434a2b8060b2d398879c26e1f9c56f488/plugins/sudoers/visudo.c#L404)

**Comment by millert** [comment]
I'm sorry but that doesn't count as a leak, there is no need to free memory before exit.  All memory is freed when the process exits.
