### ISSUE TITLE
Mention all three bug reporting methods on the man pages

### ISSUE THREAD

**Issue by jidanni** [sudo-project/sudo#377]
https://github.com/sudo-project/sudo?tab=readme-ov-file#filing-bug-reportsissues
mentions three bug reporting methods, but the man page(s) only mention one.

P.S., the correct page to edit should have a note inside its comments that indeed it is not a post-processed version of some other page, and people are welcome to submit PRs. Else it is super hard to tell which is the real source.

**Comment by millert** [comment]
Fixed by [74d64bc](https://github.com/sudo-project/sudo/commit/74d64bc8964d43f21a9f25871652984de900b98b).  The generated man pages now say which file is the original, including the .mdoc ones.  That should make it clear which file is authoratative.
