### ISSUE TITLE
user added by systemd-homed won't be able to use sudo 

### ISSUE THREAD

**Issue by sequencer** [sudo-project/sudo#41]
user won't be able to use `sudo`, since this user doesn't exist in `/etc/passwd`, `/etc/group`, and `/etc/shadow`, it can be access by `getent`, `sudo` currently cannot use identify these users.

**Comment by darkdragon-001** [comment]
Same problem when using `libnss-wrapper` (https://askubuntu.com/q/1168246/206608).

**Comment by millert** [comment]
In the case of systemd-homes, this sounds like a problem with the PAM configuration in /etc/pam.d/sudo.  Sudo itself just uses the standard C library functions to look up password and group information.  That error indicates that the user cannot be looked up by their user ID using the getpwuid(3) function.

As for libnss-wrapper, that relies on LD_PRELOAD which is ignored by the dynamic loader for set-user-ID programs like sudo.  I don't think this is an issue with sudo itself.

**Comment by sequencer** [comment]
> Sudo itself just uses the standard C library functions to look up password and group information.

I think this is the main problem for this issue. In the implementation of `systemd-homed`:
> Note that users/home directories managed via systemd-homed.service do not show up in /etc/passwd and similar files, they are synthesized via glibc NSS during runtime. They are thus resolvable and may be enumerated via the getent(1) tool.

So maybe switch to `getent` is the final solution to this.

**Comment by millert** [comment]
No, that is not a solution.  Since sudo is just using the standard glibc functions this should all just work transparently.  What is the passwd line in /etc/nsswitch.conf on your machine?

**Comment by millert** [comment]
Also, you should verify that you can look up the user-ID with getent and not just the name.  For example `getent $(id -u)`

**Comment by millert** [comment]
I have verified that a user created with homectl is able to use sudo as long as PAM is setup correctly.  I used the example from the pam_systemd_home manual.  This is on a Fedora 35 VM.

```
fedora35 [~] % homectl
NAME      UID   GID   STATE    REALNAME       HOME            SHELL
homefree2 60229 60229 inactive Home Free User /home/homefree2 /bin/bash

fedora35 [~] % su - homefree2
Password:

[homefree2@fedora35 ~]$ sudo -V
Sudo version 1.9.8p2

[homefree2@fedora35 ~]$ sudo -l
[sudo] password for homefree2:
Matching Defaults entries for homefree2 on fedora35:
    env_keep+="LANG LANGUAGE LINGUAS LC_* _XKB_CHARSET", env_keep+="QTDIR KDEDIR"

User homefree2 may run the following commands on fedora35:
    (ALL) ALL

[homefree2@fedora35 ~]$ sudo id
uid=0(root) gid=0(root) groups=0(root) context=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023
```
