### ISSUE TITLE
Sudo Password and SSH connection

### ISSUE THREAD

**Issue by Sidzeppelin95** [sudo-project/sudo#410]
While using any sudo commands I am prompted for a password that I did not set which does not let me proceed with anything. I am also getting the connection refusal error saying ssh: connect to my host: connection refused
The following errors while installling using apt: 
The virtual environment was not created successfully because ensurepip is not
available.  On Debian/Ubuntu systems, you need to install the python3-venv
package using the following command.

    apt install python3.10-venv

You may need to use sudo with that command.  After installing the python3-venv
package, recreate your virtual environment.

Failing command: /home/devcontainers/openvino/bin/python3
~$ apt install python3.10-venv
E: Could not open lock file /var/lib/dpkg/lock-frontend - open (13: Permission denied)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), are you root?
I am not sure whats going on here so I need some advice.

**Comment by millert** [comment]
By default, sudo requires the user's own password, assuming they are allowed to run sudo by the /etc/sudoers file.

**Comment by Sidzeppelin95** [comment]
Well it does but I didn't create the password here. If someone else did,
they should provide it so I can access it.
