### ISSUE TITLE
Site being scanned by SCANOSS

### ISSUE THREAD

**Issue by VegaDeftwing** [sudo-project/sudo#413]
Hello, I saw that SCANOSS was scanning sudo.ws ( They brag about it on https://www.softwaretransparency.org/osskb ) I was curious if they'd gotten permission to do this?

**Comment by millert** [comment]
Nobody contacted me about scanning sudo.ws but I suppose it is not much different from other web crawlers indexing the site.  I'm not sure what they are getting out of it that they couldn't just get from GitHub.

**Comment by VegaDeftwing** [comment]
I'm curious myself. I ask because they're, uh, being less than civil with open source projects right now. https://github.com/scanoss/purl2cpe/issues/24 /  https://news.ycombinator.com/item?id=41735407 just trying to get an idea about how they operate.

Thank you for the fast reply!
