### ISSUE TITLE
Just wondering

### ISSUE THREAD

**Issue by SleepTheGod** [sudo-project/sudo#422]
root@vps-a1d18fab:~# curl -sSL https://www.sudo.ws/ftp/etc/passwd
<html>
<head><title>403 Forbidden</title></head>
<body>
<center><h1>403 Forbidden</h1></center>
<hr><center>nginx</center>
</body>
</html>
root@vps-a1d18fab:~#

Why does this say forbidden now?

When it used to say this

curl https://www.sudo.ws/ftp/etc/passwd
root::0:0:Charlie &:/root:/bin/csh
daemon::1:31:The devil himself:/root:/sbin/nologin
operator::2:5:System &:/operator:/sbin/nologin
bin::3:7:Binaries Commands and Source,,,:/:/sbin/nologin
www::67:67:HTTP server:/var/www:/sbin/nologin
ftp::98:20:Anonymous FTP:/usr/home/ftp:/usr/bin/false
nobody::32767:32767:Unprivileged user:/nonexistent:/sbin/nologin
millert::8036:20:Todd C. Miller:/usr/home/millert:/usr/local/bin/tcsh
curl -sSL https://www.sudo.ws/ftp/etc/group
wheel::0:root
daemon::1:daemon
kmem::2:root
sys::3:root
tty::4:root
operator::5:root
bin::7:
news::8:
wsrc::9:
users::10:
games::13:
staff::20:root
guest::31:root
utmp::45:
www::67:
network::69:
named::70:
dialer::117:
nogroup::32766:
nobody::32767:
curl -sSL https://www.sudo.ws/ftp/etc/passwd
root::0:0:Charlie &:/root:/bin/csh
daemon::1:31:The devil himself:/root:/sbin/nologin
operator::2:5:System &:/operator:/sbin/nologin
bin::3:7:Binaries Commands and Source,,,:/:/sbin/nologin
www::67:67:HTTP server:/var/www:/sbin/nologin
ftp::98:20:Anonymous FTP:/usr/home/ftp:/usr/bin/false
nobody::32767:32767:Unprivileged user:/nonexistent:/sbin/nologin
millert::8036:20:Todd C. Miller:/usr/home/millert:/usr/local/bin/tcsh

and this was my report on it?

https://github.com/sudo-project/sudo/issues/215

**Comment by SleepTheGod** [comment]
![image](https://github.com/user-attachments/assets/d2f323bf-9611-4231-98e0-9824b0b7bb63)

**Comment by millert** [comment]
I got tired of people trying to report this as a security issue when it is not one (there is no sensitive information in those files, despite what some people seem to think).  Now only the files in /ftp/pub are accessible.

**Comment by millert** [comment]
Actually, there's no real reason to expose /ftp on www.sudo.ws anymore--all access to /ftp/pub/sudo should be via /dist these days.
