### ISSUE TITLE
Please support a password of 500 characters

### ISSUE THREAD

**Issue by Rangtian** [sudo-project/sudo#43]
sudo kept telling me that "Sorry, try again" when I copied and pasted my password. Then I change my password to "Qwer1234^", it worked perfectly.

So I guess a password of 500 characters is just too long for sudo?

**Comment by millert** [comment]
The pasword limit for sudo 1.8.x is 255 characters.  For sudo 1.9.0 it will be increased to 1023 characters.

**Comment by Rangtian** [comment]
@millert Thank you. Case closed.
