### ISSUE TITLE
LD_PRELOAD is ignored by sudo

### ISSUE THREAD

**Issue by darkdragon-001** [sudo-project/sudo#46]
@millert wrote in https://github.com/sudo-project/sudo/issues/41#issuecomment-617387631:
> As for libnss-wrapper, that relies on LD_PRELOAD which is ignored by the dynamic loader for set-user-ID programs like sudo. I don't think this is an issue with sudo itself.

Are there any alternatives to solve the use case described [here](https://askubuntu.com/q/1168246/206608):
A docker container which is run via `docker run -u UID` should somehow create a user on startup. Even the entrypoint script is run with that user and doesn't have root permissions. `sudo` relies on some system functionality to resolve the UID to a user name. How can this be provided?

**Comment by millert** [comment]
It is not sudo that is ignoring LD_PRELOAD, it is the dynamic loader itself.  It does this for a good reason--it would be extremely insecure to allow the user to override arbitrary functions in a set-user-ID executable (which is what you are trying to do).  The way to achieve what you want is to write a proper nss module and use that in /etc/nsswitch.conf.  Something like the NSS altfiles module should be able to do that.
