### ISSUE TITLE
"This incident will be reported" wording

### ISSUE THREAD

**Issue by es20490446e** [sudo-project/sudo#48]
Perhaps the wording of [this](https://forum.manjaro.org/uploads/default/original/3X/d/3/d35959c728f41a3db153d8ca4eadd59d039e4e72.png) could be improved (or removed all together).

**Comment by chuhn** [comment]
The link is broken

**Comment by es20490446e** [comment]
The website broke down.

Basically it was about sudo saying "this incident will be reported". That message really says nothing useful and causes confusion to most users.

**Comment by speed47** [comment]
Sorry, but I have to. Obligatory xkcd: https://xkcd.com/838/

**Comment by millert** [comment]
That text was added long ago to let the user know that an email had been sent to the admin reporting the attempt to run sudo.  Now that the log and mail settings are configurable it may no longer be useful.  I'll consider dropping that sentence in a future sudo release.

**Comment by jxu** [comment]
THIS INCIDENT WILL BE REPORTED

or will it? The NEWS file says the text was dropped.

**Comment by millert** [comment]
The text was dropped in sudo 1.9.10 which is currently in beta.
