### ISSUE TITLE
I/O plugin eats all input

### ISSUE THREAD

**Issue by guillemj** [sudo-project/sudo#5]
Hi!

It looks like sudo is eating up all input when using a pseudo-tty triggered by usage of an I/O plugin. An easy way to reproduce with the default sudoers plugins is by setting `Defaults log_input` there. And then executing in bash something like:

  ```
  $ while read -r x ; do sudo echo $x; done < <(echo -e "aaa\nbbb\nccc\n")
  aaa
  ```

The first read eats «aaa», then sudo eats  «bbb» and «ccc», which passes to the inner echo, which ignores it, then on the next loop iteration the read gets an EOF.

A partial workaround for a custom plugin is to disable itself by returning 0 in its open method, but then that makes it unable to use its close method too, which might be undesirable. I've skimmed over the code, and I don't think this is really generally fixable whenever there are logging methods in place? But it would be nice for this to work at least when all log methods are set to NULL, perhaps by only calling exec_pty (instead of exec_nopty) only when there's at least one log method set?

**Comment by ToddMiller1** [comment]
Fixed by e91e5ee820355e96826323bc1f021dff04c7e4b6
