### ISSUE TITLE
Change /var/log/sudo-io logging directory

### ISSUE THREAD

**Issue by barzilouik** [sudo-project/sudo#54]
Hello!

How can I change the default sudoreplay logging directory?
I could not find anything in the documentation and I am quite confused by the sudoreplay manual that mentions a command line flag to change that directory, is it only for reading the logs? Otherwise, nothing else I could find.

Thank you

**Comment by millert** [comment]
You can change this in sudoers.  For example, to change the directory to /var/log/sudo/iolog:

Defaults iolog_dir=/var/log/sudo/iolog

The iolog_dir setting also supports some escape sequences as documented in the sudoers manual.

**Comment by barzilouik** [comment]
Thank you!
