### ISSUE TITLE
Let developers give a reason for needing sudo

### ISSUE THREAD

**Issue by Mchar7** [sudo-project/sudo#55]
I was working on a script and had this idea, so I just thought why not mention it.

It would be nice to have an argument that lets a developer add a reason for wanting superuser privileges in their scripts. This would let them be more transparent to users as to why `sudo` is needed. You could also have the reason added to the system log.

Of course, this wouldn't stop someone from using superuser privileges for something malicious, but it would be nice to know why a script/program from a trusted source is requesting superuser privileges.

Example:
A script is being used to install _x_ program on a Debian-based system and `sudo` is needed to install dependencies via `apt`:

`sudo -r "Need to install dependencies" apt install pkg1 pkg2...`

(Potential) Result:
`[sudo] Reason: Need to install dependencies.`  
`[sudo] password for user:`

**Comment by orbea** [comment]
Why not just use `printf` or `echo`?

**Comment by 10maurycy10** [comment]
```bash
echo -n "[PACKAGE INSTALLATION], " && sudo pacman -S pkg1 pkg2
```

**Comment by Mchar7** [comment]
Forgot I had opened this. I agree now that it would be best to do this manually than adding features to a utility that should be as simple as possible. Closing.
