### ISSUE TITLE
Remove .sudo_as_admin_successful file from home folder. 

### ISSUE THREAD

**Issue by BeatLink** [sudo-project/sudo#56]
Surely there must be some other way to check if the user is running sudo for the first time. Googling the file name as is, specificially ".sudo_as_admin_successful" will show the entire first page being devoted to removing the file. It is clear that many users find the file annoying and cluttering. Not to mention that it does not follow linux filesystem and XDG folder conventions. 

Alternatively, default to not enabling the flag that creates the file

**Comment by millert** [comment]
That was a Ubuntu-specific change that I adopted,; it is only enabled on Ubuntu.  I'll consider making it configurable in sudoers.

**Comment by ttccourt** [comment]
> That was a Ubuntu-specific change that I adopted, it is only enabled on Ubuntu. I'll consider making it configurable in sudoers.

Not to beat a dying horse, but-- could this please, please be implemented? Or at least move the file to somewhere that follows the XDG Base Directory Specification?

Thank you :)

**Comment by millert** [comment]
The next sudo release will contain the linked commit that makes this configurable.  Blame Ubuntu for the path :-)

**Comment by BeatLink** [comment]
Thank you!

**Comment by roysubs** [comment]
> Blame Ubuntu for the path :-)

Are you talking about the `~/.sudo_as_admin_successful` path, or are you talking about some new location for where Ubuntu are going to put the flag? i.e. can you describe what the new behaviour will be (maybe it's even more annoying than the old behaviour!? 🤔

**Comment by millert** [comment]
@roysubs The original complaint was that `.sudo_as_admin_successful` is located in the user's home directory.  In sudo 1.9.6 the path can be changed or the feature disabled by using the _admin_flag_ setting in the sudoers file.

**Comment by roysubs** [comment]
Excellent, I will make that _admin_flag_ change immediately then as I tend to like a clean environment, and that long name sticks out like a sore thumb on every Ubuntu system. Great to see this update, as the OP pointed out, it's virtually the only thing that thousands of users for 12+ years have asked for "how do we get rid of this??". Do we expect this in Ubuntu 21.10 or will it be sooner? I'm really unclear how I will know when this update is available for us to use...

**Comment by geekley** [comment]
> or the feature disabled by using the admin_flag setting

Sorry if these are dumb questions, but could someone explain it a little more? By disabling it, you mean something like this?
`/etc/sudoers.d/disable_admin_file_in_home`
```sh
# Disable ~/.sudo_as_admin_successful file
Defaults !admin_flag
```

What happens when it's disabled? Will the message below still appear every time when the file is absent?
```
To run a command as administrator (user "root"), use "sudo <command>".
See "man sudo_root" for details.
```
If so, is there some setting that disables both the file and the message (on Ubuntu)?
Like setting it to empty string or true or something like that?
```sh
Defaults admin_flag=""
```
```sh
Defaults admin_flag
```
Or is changing the path the only way?
(I can't test it here yet because on Kubuntu 21.10 sudo -V says it's version 1.9.5p2)

**Comment by millert** [comment]
That message comes from the `/etc/bash.bashrc` file which looks for `$HOME/.sudo_as_admin_successful` and displays a message if it doesn't exist.  If you tell sudo not to create the admin flag file (and it doesn't already exist) then you will always receive that message from bash unless you modify `/etc/bash.bashrc`.

Of course, you can simply create the file yourself to disable the message, for example:
```
touch ~/.sudo_as_admin_successful
```

**Comment by geekley** [comment]
Ah I see. Thanks!
Hopefully in a future Ubuntu version they could just change that path to somewhere else in both bashrc and sudoers ...

**Comment by perlun** [comment]
> it is only enabled on Ubuntu

For reference, this has been enabled on Debian nowadays as well: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1006273. (Thanks to [pipe](https://askubuntu.com/questions/813942/is-it-possible-to-stop-sudo-as-admin-successful-being-created?noredirect=1#comment2727940_813942) for letting me know about it)
