### ISSUE TITLE
NOPASSWD not working during ssh username contains colon

### ISSUE THREAD

**Issue by Blueve** [sudo-project/sudo#64]
I am trying to execute some command via ssh or bash.bashrc, but a password prompt pop unexpected.

## Steps to Repro:

1. Update service side sudo configuration `sudo visudo`

```
%admin ALL=(ALL) NOPASSWD:ALL
```

1. Regular login with `ssh testuser@localhost 'sudo echo 777'`

```
jika@JIKA-PC:/etc$ ssh testuser@localhost 'sudo echo 777'
testuser@localhost's password:
```

Only 1 password prompt for ssh user authentication. The sudo command executed without password. This is expected.

1. Login with `ssh -t testuser:12@localhost 'sudo echo 777'`

```
jika@JIKA-PC:/etc$ ssh -t testuser:12@localhost 'sudo echo 777'
testuser:12@localhost's password: 
[sudo] password for testuser: 
```

The first password prompt is for ssh user authentication which is expected. But the second password prompt is unexpected since we have configued NOPASSWD.

**Comment by millert** [comment]
Did you really create a user name with a ':' in it or does the ":12" has some other meaning? Historically, it's been impossible to have a ':' in the user name since that's the passwd database field separator.  I would expect weird behavior if you are actually using user names that contain a ':' character.

**Comment by Blueve** [comment]
> Did you really create a user name with a ':' in it or does the ":12" has some other meaning? Historically, it's been impossible to have a ':' in the user name since that's the passwd database field separator. I would expect weird behavior if you are actually using user names that contain a ':' character.

No. sshd will split the username by colon and use the left part for authentication and put the right to it context (see here: https://github.com/openssh/openssh-portable/blob/master/auth2.c#L280)

Just like the sample I put previously, the sudo is asking a password for `testuser` instead of `testuser:12`, that's why I raise this issue here... suppose we don't prompt password for `testuser` according to my sudo configuration.

> **testuser:12**@localhost's password: 
> [sudo] password for **testuser**: 

Above behavior shows that sudo is acutally use `testuser` instead `testuser:12`.

**Comment by millert** [comment]
Yes, the `:style` bit is used for BSD authentication which is why I was surprised to see it here, I didn't realize OpenSSH portable supported that too.  Sudo looks up the user by ID, not name, so specifying a login style shouldn't be affecting anything.  Is the command allowed if you do enter the password for testuser?

**Comment by millert** [comment]
Works for me as expected with sudo 1.9.2 on Ubuntu 20.04:

```
linux-build [~] % ssh -t testuser:12@localhost 'sudo echo 777'
testuser:12@localhost's password:
777
Connection to localhost closed.
```
Can you tell me more about what OS you are running and what version of sudo you see the problem with?

**Comment by Blueve** [comment]
Ahh... I know what the problem happens here.
My configuration is wrong, there is another rule overridden my NOPASSWD rule.
Re-test and all works well after fixed configuration.

Thanks and sorry for the bothering...
