### ISSUE TITLE
Missing manpage

### ISSUE THREAD

**Issue by radosroka** [sudo-project/sudo#66]
Hello,

I'm trying to rebase sudo from 1.9.2 to 1.9.3p1 for fedora distro and file

```/usr/share/man/man8/sudo_plugin_python.8.gz```

seems to be gone.

 Actually file is in the repo but it does not appear in the .rpm as it did with 1.9.2 tarball.

**Comment by millert** [comment]
That file should only be present if sudo is configured using --enable-python.  If you don't build the sudo python plugin, the man page for it won't be installed.  This is related to Issue #58

**Comment by radosroka** [comment]
Thanks!
