### ISSUE TITLE
No sudo upgrade after installation

### ISSUE THREAD

**Issue by rnicolas** [sudo-project/sudo#75]
Operating System: Mac OS High Sierra (10.13)
sudo version before upgrade: 1.8.29
sudo version expected after upgrade: 1.9.4

After installing sudo-1.9.4.mac1013.pkg and then sudo-logsrvd-1.9.4.mac1013.pkg and rebooting my computer, when I type sudo --version I still see sudo 1.8.29, but I get the following output:

```
sudo --version
sudo: setrlimit(8): Invalid argument
Sudo version 1.8.29
sudo: error in /etc/sudo.conf, line 16 while loading plugin "sudoers_audit"
sudo: unable to find symbol "sudoers_audit" in sudoers.so
sudo: fatal error, unable to load plugins
```

**Comment by millert** [comment]
That package installs /usr/local/bin/sudo.  Try running that directly or adding /usr/local/bin to your PATH ahead of /usr/bin.

**Comment by millert** [comment]
Unfortunately, it's not really possible to replace the system binary /usr/bin/sudo as it would just be overwritten by the next macOS upgrade.  You can safely remove (or move) the /etc/sudo.conf file that the package installed which will prevent the system version of sudo from giving you that error.

**Comment by rnicolas** [comment]
> That package installs /usr/local/bin/sudo. Try running that directly or adding /usr/local/bin to your PATH ahead of /usr/bin.

Thanks, changing the order and putting /usr/local/bin ahead of /usr/bin in /etc/paths solves the problem.
