### ISSUE TITLE
`sudo` always seem to create a "monitor" process

### ISSUE THREAD

**Issue by cipriancraciun** [sudo-project/sudo#76]
I'm using OpenSUSE Tumbleweed, which just updated `sudo` to v1.9.4.  Previously I would assume I had at least v1.9.2 given how quickly packages get into Tumbleweed repositories.

However even though currently I have `Defaults !use_pty, !pam_session, !pam_setcred` in my `/etc/sudoers` file (and there are no other files under `/etc/sudoers.d`), `sudo` always seems to start a monitor process that waits for the executed one to finish.  Previously those options disabled this monitor process.

I have just downgraded `sudo` to 1.8.22 and the issue doesn't seem to be present, thus my assumption is that something broke in the latest 1.9.x releases, or perhaps there is another option enabled by default that requires a monitor process.

**Comment by millert** [comment]
Thanks for the report, this is fixed by 5c66e95
