### ISSUE TITLE
setrlimit  message

### ISSUE THREAD

**Issue by spacexnasa** [sudo-project/sudo#8]
os:mojave 10.15.1
sudo  version 

https://www.sudo.ws/sudo/dist/packages/macOS/10.15/sudo-1.8.29.mac1015.pkg

sudo -l
sudo: setrlimit(8): Invalid argument

display this message 

if /usr/bin/sudo -l ,no message like this 
sudo: setrlimit(8): Invalid argument

and can not use touch id 

/etc/pam.d/sudo   

auth       optional       pam_reattach.so
auth       sufficient     pam_tid.so

...........

the old can work

**Comment by millert** [comment]
This was fixed in 0d8062c100a3852af4ee488245ef2923c5782b96

**Comment by spacexnasa** [comment]
> This was fixed in [0d8062c](https://github.com/sudo-project/sudo/commit/0d8062c100a3852af4ee488245ef2923c5782b96)

thanks,maybe need release the file again,because when i download and run sudo-1.8.29.mac1015.pkg ,and still display this message

**Comment by millert** [comment]
I just uploaded new macOS packages with the fix so if you download again the warning should be gone.

**Comment by spacexnasa** [comment]
> I just uploaded new macOS packages with the fix so if you download again the warning should be gone.



thanks for your effort, the warning gone

**Comment by bestlong** [comment]
macOS Catalina 10.15.3 `sudo: setrlimit(8): Invalid argument`

<img width="424" alt="截圖 2020-02-17 16 50 59" src="https://user-images.githubusercontent.com/4023909/74637877-d4363f00-51a5-11ea-858b-01482f15ce4c.png">

**Comment by millert** [comment]
@bestlong What version of sudo are you using?

**Comment by bestlong** [comment]
@millert 
```shell
sudo -V
sudo: setrlimit(8): Invalid argument
Sudo version 1.8.29
Sudoers policy plugin version 1.8.29
Sudoers file grammar version 46
Sudoers I/O plugin version 1.8.29
```

**Comment by millert** [comment]
@bestlong This was fixed in Sudo 1.8.30

**Comment by bestlong** [comment]
after install sudo-1.8.31.mac1015.pkg fixed my problem.

**Comment by claytonchew** [comment]
This is not fixed at version 1.8.31. This error kept showing up each time it prompts for user password. Sometimes it floats my CLI with bunch of this error.

Current Version: 

```
$ sudo --version
Sudo version 1.8.31
Sudoers policy plugin version 1.8.31
Sudoers file grammar version 46
Sudoers I/O plugin version 1.8.31
```

**Comment by sabeelmuttil** [comment]
how to update my sudo on mac os

**Comment by bestlong** [comment]
@sabeelmuttil 
https://github.com/sudo-project/sudo/releases
download sudo-1.8.31.macXXXX.pkg
XXXX is your macOS version

**Comment by cjconstante** [comment]
Yes, it worked after update the package. Even, this fixed a locale/codification setting that I couldn't fix before.

**Comment by wwek** [comment]
sudo --version
**sudo: setrlimit(8): Invalid argument**
Sudo version 1.8.29
Sudoers policy plugin version 1.8.29
Sudoers file grammar version 46
Sudoers I/O plugin version 1.8.29


fix version


sudo --version
Sudo version 1.8.31
Sudoers policy plugin version 1.8.31
Sudoers file grammar version 46
Sudoers I/O plugin version 1.8.31



Tks

**Comment by simonliu009** [comment]
Thank you. I had the same problem after upgrading from MacOS 10.15.2 to 10.15.3. Updated sudo to 1.8.31 fixed the issue.
