### ISSUE TITLE
plugins/sudoers/editor.c wordsplit() can be off by one depending on string

### ISSUE THREAD

**Issue by sohomdatta1** [sudo-project/sudo#99]
Discovered this bug while I was trying to read the source code to figure out how sudo works inspired by @Liveoverflow's video on this topic :)

In ```plugins/sudoers/editor.c``` line 74-78 appear to increment the pointer ```*cp``` by two when a `\` is encountered (once before the continue statement, once before the start of the next iteration).  So when the environment variable ```EDITOR``` is set using ```export EDITOR='/usr/bin/vi\\'```, ```*last``` in Line 85 is set to a location that is 1 + the length of the string which is beyond the NULL pointer for that string.

Convenience link to the code in question:
https://github.com/sudo-project/sudo/blob/a85c6b41a68714f55622d83c94b76c902b251546/plugins/sudoers/editor.c#L73-L85

**Comment by millert** [comment]
Thanks, this is now fixed.  It is possible to read a single byte past the NUL but it doesn't appear to be a security issue.
